export const MARMARAY_ISTASYONLARI = [
  'Halkalı',
  'Mustafa Kemal',
  'Küçükçekmece',
  'Florya',
  'Florya Akvaryum',
  'Yeşilköy',
  'Yeşilyurt',
  'Ataköy',
  'Bakırköy',
  'Yenimahalle',
  'Zeytinburnu',
  'Kazlıçeşme',
  'Yenikapı',
  'Sirkeci',
  'Üsküdar',
  'Ayrılık Çeşmesi',
  'Söğütlüçeşme',
  'Acıbadem',
  'Ünalan',
  'Göztepe',
  'Feneryolu',
  'Bostancı',
  'Küçükyalı',
  'İdealtepe',
  'Süreyya Plajı',
  'Maltepe',
  'Cevizli',
  'Atalar',
  'Kartal',
  'Yunus',
  'Pendik',
  'Tersane',
  'Güzelyalı',
  'Aydıntepe',
  'İçmeler',
  'Tuzla',
  'Çayırova',
  'Osmangazi',
  'Gebze',
] as const;

export type MarmarayIstasyon = (typeof MARMARAY_ISTASYONLARI)[number];
